# frozen_string_literal: true

source "https://rubygems.org"

gem 'rspec', '~> 3.4'
gem 'site_prism', '~> 5.0', '>= 5.0.2'
gem 'webdrivers', '~> 5.3', '>= 5.3.1'
gem 'byebug', '~> 11.1', '>= 11.1.3'
gem 'capybara', '~> 3.40'